// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/com/fzc/domain/Person.proto

package com.fzc.domain.proto;

/**
 * Protobuf type {@code PersonProto}
 */
public  final class PersonProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PersonProto)
    PersonProtoOrBuilder {
  // Use PersonProto.newBuilder() to construct.
  private PersonProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonProto() {
    firstName_ = "";
    secondName_ = "";
    age_ = 0;
    phoneNumbers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PersonProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            secondName_ = s;
            break;
          }
          case 24: {

            age_ = input.readInt32();
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              phoneNumbers_ = new java.util.ArrayList<com.fzc.domain.proto.PersonProto.PhoneNumber>();
              mutable_bitField0_ |= 0x00000008;
            }
            phoneNumbers_.add(
                input.readMessage(com.fzc.domain.proto.PersonProto.PhoneNumber.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fzc.domain.proto.PersonProto.class, com.fzc.domain.proto.PersonProto.Builder.class);
  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PersonProto.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 areaCode = 1;</code>
     */
    int getAreaCode();

    /**
     * <code>int64 phoneNumber = 2;</code>
     */
    long getPhoneNumber();
  }
  /**
   * Protobuf type {@code PersonProto.PhoneNumber}
   */
  public  static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PersonProto.PhoneNumber)
      PhoneNumberOrBuilder {
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      areaCode_ = 0;
      phoneNumber_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PhoneNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              areaCode_ = input.readInt32();
              break;
            }
            case 16: {

              phoneNumber_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_PhoneNumber_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fzc.domain.proto.PersonProto.PhoneNumber.class, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder.class);
    }

    public static final int AREACODE_FIELD_NUMBER = 1;
    private int areaCode_;
    /**
     * <code>int32 areaCode = 1;</code>
     */
    public int getAreaCode() {
      return areaCode_;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 2;
    private long phoneNumber_;
    /**
     * <code>int64 phoneNumber = 2;</code>
     */
    public long getPhoneNumber() {
      return phoneNumber_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (areaCode_ != 0) {
        output.writeInt32(1, areaCode_);
      }
      if (phoneNumber_ != 0L) {
        output.writeInt64(2, phoneNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (areaCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, areaCode_);
      }
      if (phoneNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, phoneNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fzc.domain.proto.PersonProto.PhoneNumber)) {
        return super.equals(obj);
      }
      com.fzc.domain.proto.PersonProto.PhoneNumber other = (com.fzc.domain.proto.PersonProto.PhoneNumber) obj;

      boolean result = true;
      result = result && (getAreaCode()
          == other.getAreaCode());
      result = result && (getPhoneNumber()
          == other.getPhoneNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AREACODE_FIELD_NUMBER;
      hash = (53 * hash) + getAreaCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPhoneNumber());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fzc.domain.proto.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fzc.domain.proto.PersonProto.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PersonProto.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PersonProto.PhoneNumber)
        com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_PhoneNumber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fzc.domain.proto.PersonProto.PhoneNumber.class, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder.class);
      }

      // Construct using com.fzc.domain.proto.PersonProto.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        areaCode_ = 0;

        phoneNumber_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_PhoneNumber_descriptor;
      }

      public com.fzc.domain.proto.PersonProto.PhoneNumber getDefaultInstanceForType() {
        return com.fzc.domain.proto.PersonProto.PhoneNumber.getDefaultInstance();
      }

      public com.fzc.domain.proto.PersonProto.PhoneNumber build() {
        com.fzc.domain.proto.PersonProto.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.fzc.domain.proto.PersonProto.PhoneNumber buildPartial() {
        com.fzc.domain.proto.PersonProto.PhoneNumber result = new com.fzc.domain.proto.PersonProto.PhoneNumber(this);
        result.areaCode_ = areaCode_;
        result.phoneNumber_ = phoneNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fzc.domain.proto.PersonProto.PhoneNumber) {
          return mergeFrom((com.fzc.domain.proto.PersonProto.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fzc.domain.proto.PersonProto.PhoneNumber other) {
        if (other == com.fzc.domain.proto.PersonProto.PhoneNumber.getDefaultInstance()) return this;
        if (other.getAreaCode() != 0) {
          setAreaCode(other.getAreaCode());
        }
        if (other.getPhoneNumber() != 0L) {
          setPhoneNumber(other.getPhoneNumber());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fzc.domain.proto.PersonProto.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fzc.domain.proto.PersonProto.PhoneNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int areaCode_ ;
      /**
       * <code>int32 areaCode = 1;</code>
       */
      public int getAreaCode() {
        return areaCode_;
      }
      /**
       * <code>int32 areaCode = 1;</code>
       */
      public Builder setAreaCode(int value) {
        
        areaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 areaCode = 1;</code>
       */
      public Builder clearAreaCode() {
        
        areaCode_ = 0;
        onChanged();
        return this;
      }

      private long phoneNumber_ ;
      /**
       * <code>int64 phoneNumber = 2;</code>
       */
      public long getPhoneNumber() {
        return phoneNumber_;
      }
      /**
       * <code>int64 phoneNumber = 2;</code>
       */
      public Builder setPhoneNumber(long value) {
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 phoneNumber = 2;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PersonProto.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:PersonProto.PhoneNumber)
    private static final com.fzc.domain.proto.PersonProto.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fzc.domain.proto.PersonProto.PhoneNumber();
    }

    public static com.fzc.domain.proto.PersonProto.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    public com.fzc.domain.proto.PersonProto.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int FIRSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object firstName_;
  /**
   * <code>string firstName = 1;</code>
   */
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECONDNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object secondName_;
  /**
   * <code>string secondName = 2;</code>
   */
  public java.lang.String getSecondName() {
    java.lang.Object ref = secondName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secondName_ = s;
      return s;
    }
  }
  /**
   * <code>string secondName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSecondNameBytes() {
    java.lang.Object ref = secondName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secondName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 3;
  private int age_;
  /**
   * <code>int32 age = 3;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int PHONENUMBERS_FIELD_NUMBER = 4;
  private java.util.List<com.fzc.domain.proto.PersonProto.PhoneNumber> phoneNumbers_;
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  public java.util.List<com.fzc.domain.proto.PersonProto.PhoneNumber> getPhoneNumbersList() {
    return phoneNumbers_;
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  public java.util.List<? extends com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder> 
      getPhoneNumbersOrBuilderList() {
    return phoneNumbers_;
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  public int getPhoneNumbersCount() {
    return phoneNumbers_.size();
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  public com.fzc.domain.proto.PersonProto.PhoneNumber getPhoneNumbers(int index) {
    return phoneNumbers_.get(index);
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  public com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
      int index) {
    return phoneNumbers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
    }
    if (!getSecondNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, secondName_);
    }
    if (age_ != 0) {
      output.writeInt32(3, age_);
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      output.writeMessage(4, phoneNumbers_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
    }
    if (!getSecondNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, secondName_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, age_);
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, phoneNumbers_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fzc.domain.proto.PersonProto)) {
      return super.equals(obj);
    }
    com.fzc.domain.proto.PersonProto other = (com.fzc.domain.proto.PersonProto) obj;

    boolean result = true;
    result = result && getFirstName()
        .equals(other.getFirstName());
    result = result && getSecondName()
        .equals(other.getSecondName());
    result = result && (getAge()
        == other.getAge());
    result = result && getPhoneNumbersList()
        .equals(other.getPhoneNumbersList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + SECONDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSecondName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    if (getPhoneNumbersCount() > 0) {
      hash = (37 * hash) + PHONENUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumbersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fzc.domain.proto.PersonProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fzc.domain.proto.PersonProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fzc.domain.proto.PersonProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fzc.domain.proto.PersonProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fzc.domain.proto.PersonProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PersonProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PersonProto)
      com.fzc.domain.proto.PersonProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fzc.domain.proto.PersonProto.class, com.fzc.domain.proto.PersonProto.Builder.class);
    }

    // Construct using com.fzc.domain.proto.PersonProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhoneNumbersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      firstName_ = "";

      secondName_ = "";

      age_ = 0;

      if (phoneNumbersBuilder_ == null) {
        phoneNumbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        phoneNumbersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fzc.domain.proto.OuterPersonProto.internal_static_PersonProto_descriptor;
    }

    public com.fzc.domain.proto.PersonProto getDefaultInstanceForType() {
      return com.fzc.domain.proto.PersonProto.getDefaultInstance();
    }

    public com.fzc.domain.proto.PersonProto build() {
      com.fzc.domain.proto.PersonProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.fzc.domain.proto.PersonProto buildPartial() {
      com.fzc.domain.proto.PersonProto result = new com.fzc.domain.proto.PersonProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.firstName_ = firstName_;
      result.secondName_ = secondName_;
      result.age_ = age_;
      if (phoneNumbersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phoneNumbers_ = phoneNumbers_;
      } else {
        result.phoneNumbers_ = phoneNumbersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fzc.domain.proto.PersonProto) {
        return mergeFrom((com.fzc.domain.proto.PersonProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fzc.domain.proto.PersonProto other) {
      if (other == com.fzc.domain.proto.PersonProto.getDefaultInstance()) return this;
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getSecondName().isEmpty()) {
        secondName_ = other.secondName_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (phoneNumbersBuilder_ == null) {
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbers_.isEmpty()) {
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhoneNumbersIsMutable();
            phoneNumbers_.addAll(other.phoneNumbers_);
          }
          onChanged();
        }
      } else {
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbersBuilder_.isEmpty()) {
            phoneNumbersBuilder_.dispose();
            phoneNumbersBuilder_ = null;
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            phoneNumbersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneNumbersFieldBuilder() : null;
          } else {
            phoneNumbersBuilder_.addAllMessages(other.phoneNumbers_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fzc.domain.proto.PersonProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fzc.domain.proto.PersonProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secondName_ = "";
    /**
     * <code>string secondName = 2;</code>
     */
    public java.lang.String getSecondName() {
      java.lang.Object ref = secondName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secondName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string secondName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSecondNameBytes() {
      java.lang.Object ref = secondName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secondName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string secondName = 2;</code>
     */
    public Builder setSecondName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secondName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string secondName = 2;</code>
     */
    public Builder clearSecondName() {
      
      secondName_ = getDefaultInstance().getSecondName();
      onChanged();
      return this;
    }
    /**
     * <code>string secondName = 2;</code>
     */
    public Builder setSecondNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secondName_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 3;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 3;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.fzc.domain.proto.PersonProto.PhoneNumber> phoneNumbers_ =
      java.util.Collections.emptyList();
    private void ensurePhoneNumbersIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        phoneNumbers_ = new java.util.ArrayList<com.fzc.domain.proto.PersonProto.PhoneNumber>(phoneNumbers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fzc.domain.proto.PersonProto.PhoneNumber, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder, com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder> phoneNumbersBuilder_;

    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public java.util.List<com.fzc.domain.proto.PersonProto.PhoneNumber> getPhoneNumbersList() {
      if (phoneNumbersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phoneNumbers_);
      } else {
        return phoneNumbersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public int getPhoneNumbersCount() {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.size();
      } else {
        return phoneNumbersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public com.fzc.domain.proto.PersonProto.PhoneNumber getPhoneNumbers(int index) {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.get(index);
      } else {
        return phoneNumbersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder setPhoneNumbers(
        int index, com.fzc.domain.proto.PersonProto.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, value);
        onChanged();
      } else {
        phoneNumbersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder setPhoneNumbers(
        int index, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder addPhoneNumbers(com.fzc.domain.proto.PersonProto.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder addPhoneNumbers(
        int index, com.fzc.domain.proto.PersonProto.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(index, value);
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder addPhoneNumbers(
        com.fzc.domain.proto.PersonProto.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder addPhoneNumbers(
        int index, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder addAllPhoneNumbers(
        java.lang.Iterable<? extends com.fzc.domain.proto.PersonProto.PhoneNumber> values) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumbers_);
        onChanged();
      } else {
        phoneNumbersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder clearPhoneNumbers() {
      if (phoneNumbersBuilder_ == null) {
        phoneNumbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        phoneNumbersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public Builder removePhoneNumbers(int index) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.remove(index);
        onChanged();
      } else {
        phoneNumbersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public com.fzc.domain.proto.PersonProto.PhoneNumber.Builder getPhoneNumbersBuilder(
        int index) {
      return getPhoneNumbersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index) {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.get(index);  } else {
        return phoneNumbersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public java.util.List<? extends com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder> 
         getPhoneNumbersOrBuilderList() {
      if (phoneNumbersBuilder_ != null) {
        return phoneNumbersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phoneNumbers_);
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public com.fzc.domain.proto.PersonProto.PhoneNumber.Builder addPhoneNumbersBuilder() {
      return getPhoneNumbersFieldBuilder().addBuilder(
          com.fzc.domain.proto.PersonProto.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public com.fzc.domain.proto.PersonProto.PhoneNumber.Builder addPhoneNumbersBuilder(
        int index) {
      return getPhoneNumbersFieldBuilder().addBuilder(
          index, com.fzc.domain.proto.PersonProto.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
     */
    public java.util.List<com.fzc.domain.proto.PersonProto.PhoneNumber.Builder> 
         getPhoneNumbersBuilderList() {
      return getPhoneNumbersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.fzc.domain.proto.PersonProto.PhoneNumber, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder, com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder> 
        getPhoneNumbersFieldBuilder() {
      if (phoneNumbersBuilder_ == null) {
        phoneNumbersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.fzc.domain.proto.PersonProto.PhoneNumber, com.fzc.domain.proto.PersonProto.PhoneNumber.Builder, com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder>(
                phoneNumbers_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        phoneNumbers_ = null;
      }
      return phoneNumbersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PersonProto)
  }

  // @@protoc_insertion_point(class_scope:PersonProto)
  private static final com.fzc.domain.proto.PersonProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fzc.domain.proto.PersonProto();
  }

  public static com.fzc.domain.proto.PersonProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonProto>
      PARSER = new com.google.protobuf.AbstractParser<PersonProto>() {
    public PersonProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonProto> getParserForType() {
    return PARSER;
  }

  public com.fzc.domain.proto.PersonProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

