// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/com/fzc/domain/Person.proto

package com.fzc.domain.proto;

public interface PersonProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PersonProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string secondName = 2;</code>
   */
  java.lang.String getSecondName();
  /**
   * <code>string secondName = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecondNameBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();

  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  java.util.List<com.fzc.domain.proto.PersonProto.PhoneNumber> 
      getPhoneNumbersList();
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  com.fzc.domain.proto.PersonProto.PhoneNumber getPhoneNumbers(int index);
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  int getPhoneNumbersCount();
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  java.util.List<? extends com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder> 
      getPhoneNumbersOrBuilderList();
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 4;</code>
   */
  com.fzc.domain.proto.PersonProto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
      int index);
}
